#include "instruction.h"
char* INSTRUCTION_str(INSTRUCTION instr){
    switch(instr){
        case ADD:
            return "ADD";
        case ADIW:
            return "ADIW";
        case AND:
            return "AND";
        case ANDI:
            return "ANDI";
        case ASR:
            return "ASR";
        case BCLR:
            return "BCLR";
        case BLD:
            return "BLD";
        case BRBC:
            return "BRBC";
        case BRBS:
            return "BRBS";
        case BREAK:
            return "BREAK";
        case BSET:
            return "BSET";
        case BST:
            return "BST";
        case CALL:
            return "CALL";
        case CBI:
            return "CBI";
        case COM:
            return "COM";
        case CP:
            return "CP";
        case CPC:
            return "CPC";
        case CPI:
            return "CPI";
        case CPSE:
            return "CPSE";
        case DEC:
            return "DEC";
        case DES:
            return "DES";
        case EICALL:
            return "EICALL";
        case EIJMP:
            return "EIJMP";
        case ELPM1:
            return "ELPM1";
        case ELPM2:
            return "ELPM2";
        case ELPM3:
            return "ELPM3";
        case EOR:
            return "EOR";
        case FMUL:
            return "FMUL";
        case FMULS:
            return "FMULS";
        case FMULSU:
            return "FMULSU";
        case ICALL:
            return "ICALL";
        case IJMP:
            return "IJMP";
        case IN:
            return "IN";
        case INC:
            return "INC";
        case JMP:
            return "JMP";
        case LAC:
            return "LAC";
        case LAS:
            return "LAS";
        case LAT:
            return "LAT";
        case LD1:
            return "LD1";
        case LD2:
            return "LD2";
        case LD3:
            return "LD3";
        case LDD_4:
            return "LDD_4";
        case LDD_Y2:
            return "LDD_Y2";
        case LDD_Y3:
            return "LDD_Y3";
        case LDD_Z2:
            return "LDD_Z2";
        case LDD_Z3:
            return "LDD_Z3";
        case LDD_Z4:
            return "LDD_Z4";
        case LDI:
            return "LDI";
        case LDS:
            return "LDS";
        case LPM1:
            return "LPM1";
        case LPM2:
            return "LPM2";
        case LPM3:
            return "LPM3";
        case LSR:
            return "LSR";
        case MOV:
            return "MOV";
        case MOVW:
            return "MOVW";
        case MUL:
            return "MUL";
        case MULSU:
            return "MULSU";
        case NEG:
            return "NEG";
        case NOP:
            return "NOP";
        case OR:
            return "OR";
        case ORI:
            return "ORI";
        case OUT:
            return "OUT";
        case POP:
            return "POP";
        case PUSH:
            return "PUSH";
        case RCALL:
            return "RCALL";
        case RET:
            return "RET";
        case RETI:
            return "RETI";
        case RJMP:
            return "RJMP";
        case ROL:
            return "ROL";
        case ROR:
            return "ROR";
        case SBC:
            return "SBC";
        case SBCI:
            return "SBCI";
        case SBI:
            return "SBI";
        case SBIC:
            return "SBIC";
        case SBIS:
            return "SBIS";
        case SBIW:
            return "SBIW";
        case SBRC:
            return "SBRC";
        case SBRS:
            return "SBRS";
        case SLEEP:
            return "SLEEP";
        case SPM:
            return "SPM";
        case SPM2_4:
            return "SPM2_4";
        case ST1:
            return "ST1";
        case ST2:
            return "ST2";
        case ST3:
            return "ST3";
        case STS:
            return "STS";
        case ST_Y2:
            return "ST_Y2";
        case ST_Y3:
            return "ST_Y3";
        case ST_Y4:
            return "ST_Y4";
        case ST_Z2:
            return "ST_Z2";
        case ST_Z3:
            return "ST_Z3";
        case ST_Z4:
            return "ST_Z4";
        case SUB:
            return "SUB";
        case SUBI:
            return "SUBI";
        case SWAP:
            return "SWAP";
        case WDR:
            return "WDR";
        case XCH:
            return "XCH";
        case UNKNOWN:
            return "UNKNOWN";
    }
}
