#include "instruction.h"

/*
 * Converts an instruction to its string representation
 * useful for debugging and display
 *
 * Automatically generated from the instruction listing
 */
char* instruction_str(enum instruction instr){
    switch(instr){
        case ADD:
            return "ADD";
        case ADIW:
            return "ADIW";
        case AND:
            return "AND";
        case ANDI:
            return "ANDI";
        case ASR:
            return "ASR";
        case BCLR:
            return "BCLR";
        case BLD:
            return "BLD";
        case BRBC:
            return "BRBC";
        case BRBS:
            return "BRBS";
        case BREAK:
            return "BREAK";
        case BSET:
            return "BSET";
        case BST:
            return "BST";
        case CBI:
            return "CBI";
        case COM:
            return "COM";
        case CP:
            return "CP";
        case CPC:
            return "CPC";
        case CPI:
            return "CPI";
        case CPSE:
            return "CPSE";
        case DEC:
            return "DEC";
        case EOR:
            return "EOR";
        case ICALL:
            return "ICALL";
        case IJMP:
            return "IJMP";
        case IN:
            return "IN";
        case INC:
            return "INC";
        case LDD_Y:
            return "LDD_Y";
        case LDD_Z:
            return "LDD_Z";
        case LDI:
            return "LDI";
        case LDS:
            return "LDS";
        case LD_X:
            return "LD_X";
        case LD_Xm:
            return "LD_Xm";
        case LD_Xp:
            return "LD_Xp";
        case LD_Ym:
            return "LD_Ym";
        case LD_Yp:
            return "LD_Yp";
        case LD_Zm:
            return "LD_Zm";
        case LD_Zp:
            return "LD_Zp";
        case LPM:
            return "LPM";
        case LPM_Z:
            return "LPM_Z";
        case LPM_Zp:
            return "LPM_Zp";
        case LSR:
            return "LSR";
        case MOV:
            return "MOV";
        case MOVW:
            return "MOVW";
        case NEG:
            return "NEG";
        case NOP:
            return "NOP";
        case OR:
            return "OR";
        case ORI:
            return "ORI";
        case OUT:
            return "OUT";
        case POP:
            return "POP";
        case PUSH:
            return "PUSH";
        case RCALL:
            return "RCALL";
        case RET:
            return "RET";
        case RETI:
            return "RETI";
        case RJMP:
            return "RJMP";
        case ROL:
            return "ROL";
        case ROR:
            return "ROR";
        case SBC:
            return "SBC";
        case SBCI:
            return "SBCI";
        case SBI:
            return "SBI";
        case SBIC:
            return "SBIC";
        case SBIS:
            return "SBIS";
        case SBIW:
            return "SBIW";
        case SBRC:
            return "SBRC";
        case SBRS:
            return "SBRS";
        case SLEEP:
            return "SLEEP";
        case SPM:
            return "SPM";
        case STD_Y:
            return "STD_Y";
        case STD_Z:
            return "STD_Z";
        case STS:
            return "STS";
        case ST_X:
            return "ST_X";
        case ST_Xm:
            return "ST_Xm";
        case ST_Xp:
            return "ST_Xp";
        case ST_Ym:
            return "ST_Ym";
        case ST_Yp:
            return "ST_Yp";
        case ST_Zm:
            return "ST_Zm";
        case ST_Zp:
            return "ST_Zp";
        case SUB:
            return "SUB";
        case SUBI:
            return "SUBI";
        case SWAP:
            return "SWAP";
        case WDR:
            return "WDR";
        case UNKNOWN:
        default:
            return "UNKNOWN";
    }
}
